### ISSUE TITLE
Issue with custom-activity: runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by mgdevstack** [TIBCOSoftware/flogo-contrib#146] opened 2017-11-04 05:19 UTC
We are facing **runtime error: invalid memory address or nil pointer dereference** with every custom activity. Is there anything missing?

Created a simple activity (**simpletest**) to demonstrate the issue:
https://github.com/mgdevstack/flogo-contrib/tree/master/activity/simpletest

**flogoapp to test:**  https://github.com/mgdevstack/flogo/tree/master/apps/simpleapp
flogo.json
```
{
  "name": "testingapp",
  "type": "flogo:app",
  "version": "0.0.1",
  "description": "",
  "triggers": [
    {
      "name": "Timer",
      "ref": "github.com/TIBCOSoftware/flogo-contrib/trigger/timer",
      "description": "Simple Timer trigger",
      "settings": {},
      "id": "timer",
      "handlers": [
        {
          "settings": {
            "repeating": "true",
            "notImmediate": "false",
            "startDate": "",
            "hours": "",
            "minutes": "",
            "seconds": "5"
          },
          "actionId": "sactivity"
        }
      ]
    }
  ],
  "actions": [
    {
      "name": "sactivity",
      "data": {
        "flow": {
          "type": 1,
          "attributes": [],
          "rootTask": {
            "id": 1,
            "type": 1,
            "tasks": [
              {
                "id": 2,
                "name": "activity-test",
                "description": "test activity",
                "type": 1,
                "activityType": "mgdevstack-activity",
                "activityRef": "github.com/mgdevstack/flogo-contrib/activity/simpletest",
                "attributes": [
                  {
                    "name": "input",
                    "value": "Activity Input",
                    "required": true,
                    "type": "string"
                  }
                ]
              }
            ],
            "attributes": []
          }
        }
      },
      "id": "sactivity",
      "ref": "github.com/TIBCOSoftware/flogo-contrib/action/flow"
    }
  ]
}
```
Below is the screenshot of StackTrace fetched from 
```
....github.com/mgdevstack/flogo/apps/simpleapp/vendor/src/github.com/TIBCOSoftware/flogo-contrib/action/flow/instance/instance.go:264
```
![sc2](https://user-images.githubusercontent.com/8110509/32402547-831925f6-c14c-11e7-97e9-532a7297c770.png)

![sc1](https://user-images.githubusercontent.com/8110509/32402551-8da470de-c14c-11e7-838b-40907bcf2e2f.png)

I couldn't able to debug values in channels but I'm sure we are missing to handle any error in specified go routine of execTask(workItem *WorkItem) function. Can anyone debug the issue with custom activity or this app?

Referencec:
**Activity:** https://github.com/mgdevstack/flogo-contrib/tree/master/activity/simpletest
**App:** https://github.com/mgdevstack/flogo/tree/master/apps/simpleapp

**Comment by mgdevstack** [comment] 2017-11-04 06:21
@torresashjian, Can you please have look on this as a priority issue. None of my applications are running due to this error where custom activities are involved in the flow.

I tried using docker UI to install my custom activities but it shows "install successful" but activities are not visible in UI to add.

**Comment by torresashjian** [comment] 2017-11-04 07:22
Hi @mgdevstack it seems like your activity.json in https://github.com/mgdevstack/flogo-contrib/tree/master/activity/simpletest is missing the "ref" property. Try with this:
{
  "name": "simpletest",
  "version": "0.0.1",
  "type": "flogo:activity",
  "ref": "github.com/mgdevstack/flogo-contrib/activity/simpletest",
  "description": "Simple Activity to test",
  "author": "Mayank Gaikwad <mg.devzone@gmail.com>",
  "inputs":[
    {
      "name": "input",
      "type": "string"
    }
  ],
  "outputs": [
    {
      "name": "output",
      "type": "string"
    }
  ]
}

**Comment by mgdevstack** [comment] 2017-11-04 08:31
@torresashjian, I tried with above fix, but it's not working.
https://github.com/mgdevstack/flogo-contrib/commit/c0071782b20be323063ed88d9d95480b9db339a4

Any other points to debug?

**Comment by mgdevstack** [comment] 2017-11-04 09:00
Thanks @torresashjian, I hope, the problem is resolved with your suggestion.  If ref attribute in activity.json is the reason behind this issue, we need to fix codebase to pick up activity reference from application's flogo.json (activityRef attribute) not from activity.json (ref attribute) because as earlier mentioned, we create activity first, push this to git and then reference this activity in the application.

Is it worth doing?

**Comment by mellistibco** [comment] 2017-12-12 23:57
@mgdevstack was your issue resolved? will look into the feasibility around your suggestion. perhaps @fm-tibco has some thoughts?

**Comment by mellistibco** [comment] 2018-03-13 12:43
Closing with the assumption that the issue is solved... opened a new issue TIBCOSoftware/flogo#183 to track @mgdevstack's suggestion around ref

**Closed by mellistibco** 2018-03-13 12:43 UTC
